### ISSUE TITLE
Question: What's left to make this prod ready?

### ISSUE THREAD

**Issue by zcstarr** [etclabscore/go-openrpc-reflect#1]
What's left to make this production ready?

**Comment by meowsbits** [comment]
- [ ] Probably rename the package from `go_openrpc_reflect` to something more idiomatic. Possibly `rpcreflect`? ... Still kind of ugly :grimacing: :grey_question: ...
- [ ] There were a few outstanding bugs this was waiting on in upstream dependencies:
  + github.com/open-rpc/meta-schema: `allOf`/`anyOf` support was lacking; this package uses the generated Go metaschema code for a large portion of it's JSON types, and this bug required some quite ugly workarounds. Evidence of this is, like the bullet point below, available in the `go.mod` file.
  + `replace github.com/alecthomas/jsonschema => github.com/etclabscore/go-jsonschema-reflect v0.0.2` is a symptom of another upstream bug. It's been a while now since I've looked at this, but I this issue also had to do with array annotations. Our changes should be PR'd upstream, and/or we need to decide to commit to maintaining the fork.
- [x] Since this will only ever be used as a library, we don't need to worry about packaging archive releases.
- [ ] However, we do need to establish an API definition and (subsequently) a SemVer application pattern and code versioning pattern (eg. `/v1`). How are we going to manage versions?
- [ ] As always, improving documentation -- at least as far as some Quick-Start instructions in the README beside the example -- would be welcome. 

Can you think of or see anything else?
